# Hardware configuration for Jetson Orin Nano (jetson-2)
# This file is usually generated by nixos-generate-config
# Manual configuration for Jetson Orin Nano development kit

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # Boot configuration handled by jetson-orin-nano.nix module
  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # Network interfaces (typical for Jetson Orin Nano)
  # eth0: Built-in Gigabit Ethernet
  # Additional interfaces via USB adapters

  # CPU configuration
  nix.settings.max-jobs = lib.mkDefault 6; # 6-core ARM Cortex-A78AE
  nix.settings.cores = lib.mkDefault 12; # Can handle 2 threads per core

  # Platform
  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";

  # Hardware capabilities
  hardware.enableRedistributableFirmware = lib.mkDefault true;

  # Power management
  powerManagement.cpuFreqGovernor = lib.mkDefault "ondemand";
}
