name: n3x-infra
runtime: go
description: AWS infrastructure for n3x build runners

config:
  aws:region:
    description: AWS region for runner deployment
    default: us-east-1

  n3x:amiX86:
    description: Custom NixOS AMI ID for x86_64 runner (required, built via system.build.images.amazon)
    secret: false

  n3x:amiArm64:
    description: Custom NixOS AMI ID for Graviton runner (optional, omit to skip Graviton)
    secret: false

  n3x:sshPublicKey:
    description: SSH public key for remote management (required)
    secret: false

  n3x:sshCidrBlocks:
    description: CIDR block for SSH/HTTPS access (restrict in production)
    default: "0.0.0.0/0"

  n3x:rootVolumeSize:
    description: Root EBS volume size in GB
    default: 50

  n3x:cacheVolumeSize:
    description: Cache EBS volume size in GB (ZFS pool for /nix/store)
    default: 500

  n3x:yoctoVolumeSize:
    description: Yocto cache EBS volume size in GB (DL_DIR/SSTATE_DIR)
    default: 100

  n3x:instanceTypeX86:
    description: EC2 instance type for x86_64 runner
    default: c6i.2xlarge

  n3x:instanceTypeGraviton:
    description: EC2 instance type for Graviton runner
    default: c7g.2xlarge
