# isar-k3s base configuration
# Usage: kas-container build kas/base.yml:kas/machine/<target>.yml

header:
  version: 14

build_system: isar

repos:
  isar:
    url: https://github.com/ilbers/isar.git
    commit: 16b7b7e37b54be969453466e01ce4aa66e8ccb8e
    layers:
      meta:
      meta-isar:

  this:
    path: .
    layers:
      meta-isar-k3s:

# Default target - override in machine configs
# Note: Isar multiconfigs use short distro names (bookworm, not debian-bookworm)
target: isar-image-base

# Common variables
local_conf_header:
  shared-cache: |
    # Shared user-level cache directories for all Yocto/ISAR projects
    # This enables cache reuse across multiple projects/builds
    # BitBake auto-creates these directories if they don't exist
    DL_DIR = "${HOME}/.cache/yocto/downloads"
    SSTATE_DIR = "${HOME}/.cache/yocto/sstate"

  isar-k3s-base: |
    # isar-k3s common configuration
    DISTRO_APT_PREMIRRORS = ""

  isar-k3s-parallelism: |
    # Parallelism settings for build performance
    # BB_NUMBER_THREADS: concurrent BitBake tasks (recipe-level parallelism)
    # PARALLEL_MAKE: -j flag for make (within-recipe parallelism)
    # These auto-detect based on available cores if not set
    # Explicitly setting them can help with memory-constrained systems
    #
    # Default: BitBake auto-detects from os.cpu_count()
    # For 20-core systems, consider:
    #   BB_NUMBER_THREADS = "16"  # Leave headroom for system
    #   PARALLEL_MAKE = "-j 16"   # Match BB_NUMBER_THREADS

  isar-k3s-compression: |
    # Use pigz for parallel gzip compression (significantly faster on multi-core)
    # This replaces single-threaded gzip in CONVERSION_CMD:gz
    # Requires pigz to be installed in the build environment
    CONVERSION_DEPS:gz = "pigz"
    CONVERSION_CMD:gz = "${SUDO_CHROOT} sh -c 'pigz -f -9 -n -c -k ${IMAGE_FILE_CHROOT} > ${IMAGE_FILE_CHROOT}.gz'"

    # Use parallel xz compression (xz supports -T for threads)
    XZ_DEFAULTS ?= "-T 0"

    # Use parallel zstd compression (zstd supports -T for threads)
    ZSTD_DEFAULTS ?= "-T0 -19"
