# SOPS configuration for n3x secrets management
# This file configures how secrets are encrypted and who can decrypt them

# Define key groups - who can decrypt the secrets
keys:
  # Admin key - can decrypt all secrets
  # Generated: 2026-01-19 (keys at secrets/keys/admin.age, backup in Bitwarden)
  - &admin age1uchu7jegnrdwlulakw5p4gepmcd8v7jje2fknq7rc7pynhu9aawsw5naqt

  # Host keys - each host can only decrypt its own secrets
  # These should be the public keys corresponding to /var/lib/sops-nix/key.txt on each host
  # Generated: 2026-01-19 (keys at secrets/keys/*.age, backup in Bitwarden)
  - &n100-1 age1xag425eq5nh68vwm3qzz5quz98fna6qtfj5d5ujc86c7k790fpsqfuw2ug
  - &n100-2 age1lm2cgfnkf2d47yr8yu6yymm5s4w966rps63vz3xhfkc5hy5umfpqcz37wz
  - &n100-3 age1xst9l6dhdsswg5ddwyyastv0s3v0t6ugc3efelevam9wtqh8mawq0pa6cl

# Creation rules - define which keys can decrypt which files
# NOTE: Rules are matched in order - first match wins! More specific rules must come first.
creation_rules:
  # K3s shared secrets - all nodes need access
  - path_regex: "k3s/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-1
          - *n100-2
          - *n100-3

  # Host-specific secrets
  - path_regex: "hosts/n100-1/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-1

  - path_regex: "hosts/n100-2/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-2

  - path_regex: "hosts/n100-3/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-3

  # Network secrets (e.g., WiFi passwords, VPN configs)
  - path_regex: "network/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-1
          - *n100-2
          - *n100-3

  # Application secrets (database passwords, API keys, etc.)
  - path_regex: "apps/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-1
          - *n100-2
          - *n100-3

  # Default rule - admin can decrypt everything (MUST BE LAST - catch-all)
  - path_regex: ".*"
    key_groups:
      - age:
          - *admin