# SOPS configuration for n3x secrets management
# This file configures how secrets are encrypted and who can decrypt them

# Define key groups - who can decrypt the secrets
keys:
  # Admin key - can decrypt all secrets
  # Replace with actual age public key after running: age-keygen
  - &admin age1recdr08s72v544xsjgw3vdge258c3fu7r53jg03kn66t5acczspshucl4v

  # Host keys - each host can only decrypt its own secrets
  # These should be the public keys corresponding to /var/lib/sops-nix/key.txt on each host
  - &n100-1 age19n9ck9ka9j7x2tuukyyeatw56n82yc9yg7v74nwlqmmtc5typc8q0wwrrf
  - &n100-2 age1vsesxhxjcsnkletkdhncan8cz58qha5s66rgns6d8fdct0vg39dslflypj
  - &n100-3 age1argjl8q3kmfh39yyakjhv3zsdjy5pgs2azj7p3pq8wm92nwyuyyqfcfplz

# Creation rules - define which keys can decrypt which files
creation_rules:
  # Default rule - admin can decrypt everything
  - path_regex: ".*"
    key_groups:
      - age:
          - *admin

  # K3s shared secrets - all nodes need access
  - path_regex: "k3s/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-1
          - *n100-2
          - *n100-3

  # Host-specific secrets
  - path_regex: "hosts/n100-1/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-1

  - path_regex: "hosts/n100-2/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-2

  - path_regex: "hosts/n100-3/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-3

  # Network secrets (e.g., WiFi passwords, VPN configs)
  - path_regex: "network/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-1
          - *n100-2
          - *n100-3

  # Application secrets (database passwords, API keys, etc.)
  - path_regex: "apps/.*\\.yaml$"
    key_groups:
      - age:
          - *admin
          - *n100-1
          - *n100-2
          - *n100-3