{ config, lib, pkgs, ... }:

{
  imports = [
    # Hardware configuration generated by nixos-generate-config
    ./hardware-configuration.nix
  ];

  # System identification
  networking.hostName = "jetson-1";
  networking.hostId = "abcd0001"; # Required for ZFS if used

  # Network configuration
  networking = {
    # Define network interfaces (will be overridden by bonding module)
    interfaces = {
      # Primary network interface (varies by carrier board)
      eth0 = {
        useDHCP = false;
      };
      # Secondary network interface (if available via USB adapter)
      eth1 = {
        useDHCP = false;
      };
    };

    # Static IP configuration for management
    defaultGateway = {
      address = "10.10.10.1";
      interface = "bond0";
    };
    nameservers = [ "10.10.10.1" "1.1.1.1" ];

    # Bonded interface will be configured by network/bonding.nix module
    # This node will use:
    # - Bond IP: 10.10.10.14 (K3s)
    # - VLAN 100: 10.10.100.14 (Storage)
  };

  # K3s agent-specific configuration
  services.k3s = {
    role = "agent";

    # Server URL will be configured to point to the control plane VIP
    serverAddr = "https://10.10.10.10:6443";

    # Node labels
    extraFlags = [
      "--node-label=node-role.kubernetes.io/worker=true"
      "--node-label=hardware=jetson-orin-nano"
      "--node-label=location=edge"
      "--node-label=gpu=nvidia"
    ];

    # Node taints (optional - uncomment if you want to restrict workloads)
    # extraFlags = extraFlags ++ [
    #   "--node-taint=gpu=nvidia:NoSchedule"
    # ];
  };

  # Container runtime configuration
  virtualisation = {
    containerd = {
      settings = {
        plugins."io.containerd.grpc.v1.cri" = {
          # Enable NVIDIA runtime for GPU containers
          containerd.runtimes.nvidia = {
            runtime_type = "io.containerd.runc.v2";
            options = {
              BinaryName = "${pkgs.nvidia-container-runtime}/bin/nvidia-container-runtime";
            };
          };

          containerd.default_runtime_name = "nvidia";

          # Configure device plugins
          device_ownership_from_security_context = true;
        };
      };
    };
  };

  # Storage configuration
  fileSystems = {
    "/" = {
      device = "/dev/nvme0n1p2";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" ];
    };

    "/boot" = {
      device = "/dev/nvme0n1p1";
      fsType = "vfat";
    };

    # Data partition for Longhorn
    "/var/lib/longhorn" = {
      device = "/dev/nvme0n1p3";
      fsType = "ext4";
      options = [ "noatime" "nodiratime" ];
    };
  };

  # Swap configuration (using zram from hardware module)
  swapDevices = [ ];

  # System packages specific to this host
  environment.systemPackages = with pkgs; [
    # Monitoring tools
    htop
    iotop
    iftop

    # Jetson-specific monitoring (requires jetpack-nixos or custom packaging)
    # jetson-stats

    # Container debugging
    cri-tools # Provides crictl
    # ctr is provided by containerd
  ];

  # Services specific to edge nodes
  services = {
    # Enable metrics collection
    prometheus.exporters.node = {
      enable = true;
      port = 9100;
      enabledCollectors = [
        "systemd"
        "processes"
        "cpu"
        "meminfo"
        "diskstats"
        "netdev"
        "thermal_zone"
      ];
    };

    # Log aggregation
    journald = {
      extraConfig = ''
        Storage=persistent
        SystemMaxUse=1G
        SystemKeepFree=2G
        MaxRetentionSec=7d
      '';
    };
  };

  # Firewall configuration
  networking.firewall = {
    enable = true;

    # Allow K3s traffic
    allowedTCPPorts = [
      6443 # K3s API
      10250 # Kubelet
      10255 # Kubelet read-only
      9100 # Node exporter
      2379 # etcd client
      2380 # etcd peer
    ];

    allowedUDPPorts = [
      8472 # Flannel VXLAN
      51820 # WireGuard (if used)
    ];

    # Allow pod network and cluster CIDR
    trustedInterfaces = [ "cni0" "flannel.1" ];

    extraCommands = ''
      # Allow forwarding for K3s
      iptables -P FORWARD ACCEPT

      # Allow traffic from pod network
      iptables -A INPUT -s 10.42.0.0/16 -j ACCEPT

      # Allow traffic from service network
      iptables -A INPUT -s 10.43.0.0/16 -j ACCEPT
    '';
  };

  # System state version
  system.stateVersion = "24.05";
}
